newIssueWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸ’–
  
  
  Thank you and congratsğŸ‰for opening your very first issue in this project.Hope you have a great time there!ğŸ˜„ 

newPRWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸ’–
  
  
  Thank you and congratsğŸ‰ for opening your first pull request.âœ¨.We will get back to you as soon as we can.ğŸ˜„

firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ğŸ‰ğŸ‰
